repositories:
  - slug: KPostOffice/thamos_sample
    token: '{GITHUB_KEBECHET_TOKEN}'
    managers:
      - name: thoth-advise
        labels: [bot, kebechet]
      - name: thoth-provenance
        labels: [bot, kebechet]
